"""Self-contained HTML report generator.

Produces a single ``report.html`` with inline CSS (no external assets, no JS
dependencies) that renders cleanly offline and adapts to light/dark. Findings
are grouped by validation state and colour-coded by severity.
"""
from __future__ import annotations

import html
import os
from collections import Counter, defaultdict

from .correlation import CorrelationEngine
from .findings_view import build_view
from .models import HostStatus, SEVERITY_ORDER, Severity, ValidationState
from .prioritize import PriorityEngine

_SEV_COLORS = {
    "critical": "#b3005e", "high": "#c62828", "medium": "#ef6c00",
    "low": "#2e7d32", "info": "#546e7a",
}

_CSS = """
:root{--bg:#f6f7f9;--card:#fff;--fg:#1c2126;--muted:#5b6672;--border:#e2e6ea;--accent:#1565c0;}
@media (prefers-color-scheme:dark){:root{--bg:#0f1419;--card:#171d24;--fg:#e6eaee;--muted:#98a4b0;--border:#252d36;--accent:#5aa2f0;}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;}
.wrap{max-width:1100px;margin:0 auto;padding:32px 20px 80px;}
h1{font-size:26px;margin:0 0 4px}h2{font-size:20px;margin:36px 0 12px;border-bottom:2px solid var(--border);padding-bottom:6px}
h3{font-size:16px;margin:18px 0 6px}
a{color:var(--accent)}
.sub{color:var(--muted);margin:0 0 20px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:16px 0}
.stat{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:14px 16px}
.stat .n{font-size:26px;font-weight:700}.stat .l{color:var(--muted);font-size:13px}
table{width:100%;border-collapse:collapse;background:var(--card);border:1px solid var(--border);border-radius:10px;overflow:hidden;margin:10px 0}
th,td{text-align:left;padding:9px 12px;border-bottom:1px solid var(--border);font-size:14px;vertical-align:top}
th{background:rgba(127,127,127,.08);font-weight:600}tr:last-child td{border-bottom:none}
.badge{display:inline-block;padding:2px 9px;border-radius:999px;color:#fff;font-size:12px;font-weight:600}
.pill{display:inline-block;padding:1px 8px;border-radius:6px;border:1px solid var(--border);font-size:12px;color:var(--muted);margin-right:4px}
.card{background:var(--card);border:1px solid var(--border);border-left-width:5px;border-radius:10px;padding:14px 16px;margin:12px 0}
.card h3{margin:0 0 6px}
.kv{color:var(--muted);font-size:13px;margin:2px 0}
.kv b{color:var(--fg)}
.mono{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:13px}
.note{background:rgba(127,127,127,.06);border:1px dashed var(--border);border-radius:8px;padding:10px 14px;color:var(--muted);font-size:13px}
.chain{font-family:ui-monospace,Consolas,monospace;font-size:13px;margin:4px 0}
footer{margin-top:50px;color:var(--muted);font-size:12px;text-align:center}
"""


def _esc(v) -> str:
    return html.escape(str(v if v is not None else ""))


def _badge(sev: str) -> str:
    c = _SEV_COLORS.get(sev, "#546e7a")
    return f'<span class="badge" style="background:{c}">{_esc(sev.upper())}</span>'


class HTMLReport:
    def __init__(self, graph, scope, config):
        self.graph = graph
        self.scope = scope
        self.config = config

    def write(self, out_dir: str) -> str:
        os.makedirs(out_dir, exist_ok=True)
        path = os.path.join(out_dir, "report.html")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(self.render())
        return path

    def render(self) -> str:
        g = self.graph
        view = build_view(
            g,
            min_severity=getattr(self.config, "report_min_severity", "info"),
            aggregate=getattr(self.config, "report_aggregate", True),
            suppress_titles=getattr(self.config, "report_suppress_titles", None),
        )
        sev_counts = view.severity_counts
        parts = [
            "<!doctype html><html lang='en'><head><meta charset='utf-8'>",
            "<meta name='viewport' content='width=device-width,initial-scale=1'>",
            "<title>netassess — Attack-Surface Report</title>",
            f"<style>{_CSS}</style></head><body><div class='wrap'>",
            "<h1>Network Attack-Surface Assessment</h1>",
            f"<p class='sub'>Authorized assessment · generated by netassess · "
            f"targets: {_esc(', '.join(self.config.targets))}</p>",
        ]
        parts.append(self._summary(g, view, sev_counts))
        parts.append(self._scope())
        parts.append(self._priority())
        parts.append(self._findings_section(view))
        parts.append(self._domains())
        parts.append(self._hosts())
        parts.append(self._http())
        parts.append(self._content())
        parts.append(self._tls())
        parts.append(self._tech())
        parts.append(self._correlation())
        parts.append(self._gaps())
        parts.append("<footer>Non-destructive assessment. Version-derived and "
                     "CVE findings are leads (NEEDS_VALIDATION) — confirm before "
                     "acting. Stay within authorized scope.</footer>")
        parts.append("</div></body></html>")
        return "".join(parts)

    # -- sections --------------------------------------------------------- #
    def _summary(self, g, view, sev_counts) -> str:
        cells = [
            ("Hosts", len(g.hosts)),
            ("Live", len(g.live_hosts())),
            ("Open ports", sum(len(h.open_ports()) for h in g.hosts.values())),
            ("HTTP services", len(g.all_http_services())),
            ("Findings", view.kept),
        ]
        kev = sum(1 for aggs in view.by_validation.values() for a in aggs if a.kev)
        s = ["<div class='grid'>"]
        for label, n in cells:
            s.append(f"<div class='stat'><div class='n'>{n}</div>"
                     f"<div class='l'>{label}</div></div>")
        if kev:
            s.append(f"<div class='stat' style='border-color:#b3005e'>"
                     f"<div class='n' style='color:#b3005e'>{kev}</div>"
                     f"<div class='l'>Actively exploited (KEV)</div></div>")
        for sev in ("critical", "high", "medium", "low", "info"):
            n = sev_counts.get(sev, 0)
            if n:
                s.append(f"<div class='stat'><div class='n'>{_badge(sev)} {n}</div>"
                         f"<div class='l'>{sev.title()} findings</div></div>")
        s.append("</div>")
        return "".join(s)

    def _scope(self) -> str:
        sm = self.scope.summary()
        return ("<h2>Scope &amp; Authorization</h2>"
                "<table><tr><th>Authorized networks</th><td class='mono'>"
                f"{_esc(', '.join(sm['included_networks']) or '(none)')}</td></tr>"
                "<tr><th>Excluded networks</th><td class='mono'>"
                f"{_esc(', '.join(sm['excluded_networks']) or '(none)')}</td></tr>"
                "<tr><th>Forbidden ports</th><td>"
                f"{_esc(sm['forbidden_ports'] or '(none)')}</td></tr>"
                "<tr><th>Authorized operations</th><td>"
                f"{sm['authorized_ops']}</td></tr>"
                "<tr><th>Denied by scope engine</th><td>"
                f"{sm['denied_ops']}</td></tr></table>"
                "<p class='note'>Only explicitly authorized targets were assessed. "
                "Hosts seen in redirects/DNS were not auto-added to scope.</p>")

    def _priority(self) -> str:
        items = PriorityEngine().prioritize(self.graph)
        rows = ["<h2>Prioritized Attack Surfaces</h2>",
                "<p class='sub'>Evidence-weighted; presence alone is never rated "
                "critical.</p><table><tr><th>#</th><th>Asset</th><th>Score</th>"
                "<th>Top severity</th><th>Why</th></tr>"]
        for i, it in enumerate(items[:25], 1):
            rows.append(f"<tr><td>{i}</td><td class='mono'>{_esc(it.asset)}</td>"
                        f"<td>{it.score}</td><td>{_badge(it.top_severity)}</td>"
                        f"<td>{_esc('; '.join(it.reasons))}</td></tr>")
        if not items:
            rows.append("<tr><td colspan='5'>No reachable services.</td></tr>")
        rows.append("</table>")
        return "".join(rows)

    def _findings_section(self, view) -> str:
        by_val = view.by_validation
        order = [
            ("Confirmed Findings", [ValidationState.CONFIRMED]),
            ("Potential Security Issues",
             [ValidationState.POTENTIAL, ValidationState.OBSERVED]),
            ("Unvalidated Findings (incl. CVE leads)",
             [ValidationState.NEEDS_VALIDATION]),
            ("False Positives", [ValidationState.FALSE_POSITIVE]),
        ]
        out = ["<h2>Findings</h2>"]
        if view.suppressed:
            out.append(f"<p class='note'>{view.suppressed} low-signal finding(s) "
                       f"hidden (suppressed titles, or below severity "
                       f"<b>{_esc(view.threshold.value)}</b>). Full detail in "
                       "report.json.</p>")
        for title, states in order:
            group = [a for st in states for a in by_val.get(st, [])]
            group.sort(key=lambda a: (SEVERITY_ORDER[a.severity], a.count),
                       reverse=True)
            out.append(f"<h3>{_esc(title)} ({len(group)})</h3>")
            if not group:
                out.append("<p class='note'>None.</p>")
                continue
            for a in group:
                out.append(self._finding_card(a))
        return "".join(out)

    def _finding_card(self, a) -> str:
        color = _SEV_COLORS.get(a.severity.value, "#546e7a")
        suffix = f" &times;{a.count} hosts" if a.count > 1 else ""
        assets_html = ", ".join(f"<span class='mono'>{_esc(x)}</span>"
                                for x in a.assets)
        kev_badge = ("<span class='badge' style='background:#b3005e'>"
                     "ACTIVELY EXPLOITED · CISA KEV</span> ") if a.kev else ""
        epss_pill = (f"<span class='pill'>EPSS {a.epss:.0%}</span>"
                     if a.epss is not None else "")
        risk_pill = (f"<span class='pill' style='border-color:{color};color:{color}'>"
                     f"risk {a.risk}/100</span>")
        return (
            f"<div class='card' style='border-left-color:{color}'>"
            f"<h3>{kev_badge}{_badge(a.severity.value)} {_esc(a.title)}{suffix}</h3>"
            f"<div class='kv'>{risk_pill}"
            f"<span class='pill'>confidence: {_esc(a.confidence.value)}</span>"
            f"{epss_pill}"
            f"<span class='pill'>validation: {_esc(a.validation.value)}</span>"
            f"<span class='pill'>category: {_esc(a.category)}</span>"
            f"<span class='pill'>source: {_esc(a.source)}</span></div>"
            f"<div class='kv'><b>Affected assets ({a.count}):</b> {assets_html}</div>"
            f"<div class='kv'><b>Description:</b> {_esc(a.description) or '-'}</div>"
            f"<div class='kv'><b>Why it matters:</b> {_esc(a.why_it_matters) or '-'}</div>"
            f"<div class='kv'><b>Impact:</b> {_esc(a.impact) or '-'}</div>"
            f"<div class='kv'><b>Remediation:</b> {_esc(a.remediation) or '-'}</div>"
            f"</div>")

    def _domains(self) -> str:
        from .domains import all_domains
        rows = all_domains(self.graph)
        if not rows:
            return ""
        out = ["<h2>Discovered Domains</h2>",
               "<p class='note'>Hostnames from all sources: reverse DNS, TLS "
               "SAN/CN, HTTP redirects, virtual hosts.</p>",
               "<table><tr><th>Domain</th><th>Seen on</th><th>Source(s)</th></tr>"]
        for name, sources, ips in rows:
            out.append(f"<tr><td class='mono'>{_esc(name)}</td>"
                       f"<td class='mono'>{_esc(', '.join(ips))}</td>"
                       f"<td>{_esc(', '.join(sources))}</td></tr>")
        out.append("</table>")
        return "".join(out)

    def _hosts(self) -> str:
        rows = ["<h2>Hosts &amp; Open Ports</h2>",
                "<table><tr><th>IP</th><th>Hostname</th><th>Role</th><th>Status</th>"
                "<th>Open ports (service)</th></tr>"]
        for ip in sorted(self.graph.hosts):
            h = self.graph.hosts[ip]
            ports = ", ".join(
                f"{p.number}/{p.service.name}" for p in h.open_ports()) or "-"
            role = h.primary_role if h.primary_role and h.primary_role != "unknown" else "-"
            rows.append(f"<tr><td class='mono'>{_esc(h.ip)}</td>"
                        f"<td>{_esc(h.hostnames[0] if h.hostnames else '-')}</td>"
                        f"<td>{_esc(role)}</td>"
                        f"<td>{_esc(h.status.value)}</td>"
                        f"<td class='mono'>{_esc(ports)}</td></tr>")
        rows.append("</table>")
        return "".join(rows)

    def _http(self) -> str:
        svcs = self.graph.all_http_services()
        if not svcs:
            return "<h2>HTTP / HTTPS Services</h2><p class='note'>None identified.</p>"
        rows = ["<h2>HTTP / HTTPS Services</h2><table><tr><th>URL</th><th>Status</th>"
                "<th>Title</th><th>Server</th><th>Technologies</th>"
                "<th>Missing sec headers</th></tr>"]
        for _h, s in svcs:
            techs = ", ".join(f"{t.name}{('/'+t.version) if t.version else ''}"
                              for t in s.technologies) or "-"
            missing = ", ".join(k for k, v in s.security_headers.items() if not v) or "none"
            rows.append(f"<tr><td class='mono'>{_esc(s.url)}</td><td>{_esc(s.status)}</td>"
                        f"<td>{_esc(s.title)}</td><td>{_esc(s.server)}</td>"
                        f"<td>{_esc(techs)}</td><td>{_esc(missing)}</td></tr>")
        rows.append("</table>")
        return "".join(rows)

    def _content(self) -> str:
        services = [(h, s) for h, s in self.graph.all_http_services()
                    if s.discovered_paths]
        if not services:
            return ""
        out = ["<h2>Discovered Web Content</h2>",
               "<p class='note'>GET-only content discovery. Sensitive paths also "
               "appear under Findings.</p>"]
        for _h, s in services:
            base = s.url.rstrip("/")
            out.append(f"<h3>{_esc(s.url)}</h3>")
            out.append("<table><tr><th>URL</th><th>Status</th><th>Category</th>"
                       "<th>Title</th></tr>")
            for p in sorted(s.discovered_paths, key=lambda x: x["path"]):
                url = p.get("url") or (base + p["path"])   # absolute location
                out.append(f"<tr><td class='mono'>{_esc(url)}</td>"
                           f"<td>{_esc(p['status'])}</td>"
                           f"<td>{_esc(p['category'])}</td>"
                           f"<td>{_esc(p.get('title',''))}</td></tr>")
            out.append("</table>")
        return "".join(out)

    def _tls(self) -> str:
        rows = ["<h2>TLS Information</h2>"]
        any_tls = False
        rows.append("<table><tr><th>Endpoint</th><th>Subject</th><th>Issuer</th>"
                    "<th>Expires</th><th>Negotiated</th><th>Problems</th></tr>")
        for ip in sorted(self.graph.hosts):
            for port, tls in sorted(self.graph.hosts[ip].tls.items()):
                any_tls = True
                exp = tls.not_after + (f" ({tls.days_to_expiry}d)"
                                       if tls.days_to_expiry is not None else "")
                rows.append(f"<tr><td class='mono'>{_esc(ip)}:{port}</td>"
                            f"<td>{_esc(tls.subject)}</td><td>{_esc(tls.issuer)}</td>"
                            f"<td>{_esc(exp)}</td>"
                            f"<td class='mono'>{_esc(tls.negotiated_protocol)} "
                            f"{_esc(tls.negotiated_cipher)}</td>"
                            f"<td>{_esc('; '.join(tls.problems) or '-')}</td></tr>")
        rows.append("</table>")
        if not any_tls:
            return "<h2>TLS Information</h2><p class='note'>No TLS endpoints analysed.</p>"
        return "".join(rows)

    def _tech(self) -> str:
        counter = Counter()
        for _h, s in self.graph.all_http_services():
            for t in s.technologies:
                counter[f"{t.name}{('/'+t.version) if t.version else ''}"] += 1
        if not counter:
            return "<h2>Technologies</h2><p class='note'>None identified.</p>"
        rows = ["<h2>Technologies</h2><table><tr><th>Technology</th><th>Instances</th></tr>"]
        for name, n in counter.most_common():
            rows.append(f"<tr><td>{_esc(name)}</td><td>{n}</td></tr>")
        rows.append("</table>")
        return "".join(rows)

    def _correlation(self) -> str:
        chains = CorrelationEngine().correlate(self.graph)
        if not chains:
            return ""
        out = ["<h2>Correlation</h2>"]
        for c in chains:
            extra = (f" &nbsp;→ <b>{_esc(', '.join(c.findings))}</b>"
                     if c.findings else "")
            out.append(f"<div class='chain'>{_esc(c.chain())}{extra}</div>")
        return "".join(out)

    def _gaps(self) -> str:
        gaps = []
        unresp = [h.ip for h in self.graph.hosts.values()
                  if h.status in (HostStatus.UNRESPONSIVE, HostStatus.FILTERED)]
        if unresp:
            gaps.append(f"{len(unresp)} host(s) unresponsive/filtered — may be "
                        "firewalled, not offline.")
        if not self.config.full_port_scan:
            gaps.append("Only a curated port set was scanned (use --full-port-scan).")
        gaps.append("Deep credentialed checks, exploitation, and destructive tests "
                    "were intentionally NOT performed.")
        items = "".join(f"<li>{_esc(g)}</li>" for g in gaps)
        return f"<h2>Assessment Gaps</h2><ul>{items}</ul>"
